---
repos:
  - repo: https://github.com/ansible/ansible-lint
    rev: v26.4.0
    hooks:
      - id: ansible-lint

  - repo: meta
    hooks:
      - id: check-useless-excludes
        priority: 0
  - repo: https://github.com/biomejs/pre-commit
    rev: "v2.4.15"
    hooks:
      - id: biome-check
        name: biome
        alias: biome
        args: [--unsafe]
        priority: 0
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-symlinks
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: fix-byte-order-marker
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: debug-statements
        language_version: python3

  # GitHub Actions hooks
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.29.2
    hooks:
      - id: check-github-actions
      - id: check-github-workflows
        files: ^\.github/workflows/.*\.(yaml|yml)$
        types: [file, yaml]

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.26.0
    hooks:
      - id: gitleaks
